### ISSUE TITLE
您好助教，我是參加隊伍AIMASTERKING想請教一些問題

### ISSUE THREAD

**Issue by judadao** [willywsm1013/RNN-language-model#1]
當我在執行main.py的時候出現了以下這樣的報錯:
read data from ./data/train.txt
read data from ./data/valid.txt
Traceback (most recent call last):
   File "main.py", line 80, in <module>
      train_data = batchify(corpus.train, args.batch_size)
   File "main.py", line 73, in batchify
      data = data.narrow(0, 0, nbatch * bsz)
RuntimeError: invalid argument 4: out of range at /pytorch/torch/lib/TH/generic/THTensor.c:439
網路爬文之後仍找不到解決方法，想請問助教該如何解決

**Comment by willywsm1013** [comment]
請問你的環境和pytorch的版本為何呢?
如果照著readme的流程做還會有一樣的error嗎?

**Comment by judadao** [comment]
我的Pytorch版本為0.2.0版，python 是3.5.2 使用 pip， 環境是ubuntu
有照著步驟走，走到 main.py 就會出現這個error

**Comment by willywsm1013** [comment]
同學你好：
這個error是因為nbatch * bsz超出了data的大小，
請你檢查一下你是不是有哪裡有改到所以導致這個錯誤。
