### ISSUE TITLE
助教，不好意思想請教你一個在執行main.py上的問題。

### ISSUE THREAD

**Issue by charles1113** [willywsm1013/RNN-language-model#2]
在執行完python3 train --cuda 時出現這個錯誤，所以想請問助教該如何解決。

Traceback (most recent call last):
  File "main.py", line 174, in <module>
    train()
  File "main.py", line 144, in train
    output, hidden = model(data, hidden)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/aiuser3706/RNN-language-model/model.py", line 47, in forward
    output, hidden = self.rnn(emb, hidden)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/rnn.py", line 91, in forward
    output, hidden = func(input, self.all_weights, hx)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/_functions/rnn.py", line 343, in forward
    return func(input, *fargs, **fkwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/autograd/function.py", line 202, in _do_forward
    flat_output = super(NestedIOFunction, self)._do_forward(*flat_input)
  File "/usr/local/lib/python3.5/dist-packages/torch/autograd/function.py", line 224, in forward
    result = self.forward_extended(*nested_tensors)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/_functions/rnn.py", line 285, in forward_extended
    cudnn.rnn.forward(self, input, hx, weight, output, hy)
  File "/usr/local/lib/python3.5/dist-packages/torch/backends/cudnn/rnn.py", line 232, in forward
    fn.rnn_desc = init_rnn_descriptor(fn, handle)
  File "/usr/local/lib/python3.5/dist-packages/torch/backends/cudnn/rnn.py", line 42, in init_rnn_descriptor
    cudnn.DropoutDescriptor(handle, dropout_p, fn.dropout_seed)
  File "/usr/local/lib/python3.5/dist-packages/torch/backends/cudnn/__init__.py", line 178, in __init__
    self._set(dropout, seed)
  File "/usr/local/lib/python3.5/dist-packages/torch/backends/cudnn/__init__.py", line 203, in _set
    ctypes.c_ulonglong(seed),
  File "/usr/local/lib/python3.5/dist-packages/torch/backends/cudnn/__init__.py", line 249, in check_error
    raise CuDNNError(status)
# torch.backends.cudnn.CuDNNError: 8: b'CUDNN_STATUS_EXECUTION_FAILED'

謝謝您。

**Comment by willywsm1013** [comment]
請問你的cudnn版本為何呢?
或許是版本的問題
